kind: PersistentVolume
apiVersion: v1
metadata:
  name: notebook-volume-0
  labels:
    type: local
spec:
  storageClassName: gp2
  capacity:
    storage: 11Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/notebook-volume-0
